export const data = JSON.parse("{\"key\":\"v-1d1e3444\",\"path\":\"/study/STM32/GPIO/IO%E5%8F%A3%E4%BB%8B%E7%BB%8D.html\",\"title\":\"IO口介绍\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"IO口介绍\",\"icon\":\"file\",\"order\":1,\"author\":\"张凯博\",\"date\":\"2020-01-01T00:00:00.000Z\",\"description\":\"IO口介绍 STM32的IO口相比51而言要复杂得多，所以使用起来也困难很多。首先STM32的IO口可以由软件配置成如下8种模式： 1. 输入浮空 2. 输入上拉 3. 输入下拉 4. 模拟输入 5. 开漏输出 6. 推挽输出 7. 推挽式复用功能 8. 开漏复用功能 输入浮空 上拉/下拉电阻为断开状态，输入浮空模式下，IO 口的电平完全是由外部电路决...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/docs/study/STM32/GPIO/IO%E5%8F%A3%E4%BB%8B%E7%BB%8D.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"文档管理\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"IO口介绍\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"IO口介绍 STM32的IO口相比51而言要复杂得多，所以使用起来也困难很多。首先STM32的IO口可以由软件配置成如下8种模式： 1. 输入浮空 2. 输入上拉 3. 输入下拉 4. 模拟输入 5. 开漏输出 6. 推挽输出 7. 推挽式复用功能 8. 开漏复用功能 输入浮空 上拉/下拉电阻为断开状态，输入浮空模式下，IO 口的电平完全是由外部电路决...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"张凯博\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-01-01T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"IO口介绍\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-01-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"张凯博\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"IO口介绍\",\"slug\":\"io口介绍\",\"link\":\"#io口介绍\",\"children\":[{\"level\":3,\"title\":\"输入浮空\",\"slug\":\"输入浮空\",\"link\":\"#输入浮空\",\"children\":[]},{\"level\":3,\"title\":\"输入上拉\",\"slug\":\"输入上拉\",\"link\":\"#输入上拉\",\"children\":[]},{\"level\":3,\"title\":\"输入下拉\",\"slug\":\"输入下拉\",\"link\":\"#输入下拉\",\"children\":[]},{\"level\":3,\"title\":\"模拟输入\",\"slug\":\"模拟输入\",\"link\":\"#模拟输入\",\"children\":[]},{\"level\":3,\"title\":\"开漏输出\",\"slug\":\"开漏输出\",\"link\":\"#开漏输出\",\"children\":[]},{\"level\":3,\"title\":\"推挽输出\",\"slug\":\"推挽输出\",\"link\":\"#推挽输出\",\"children\":[]},{\"level\":3,\"title\":\"开漏复用功能\",\"slug\":\"开漏复用功能\",\"link\":\"#开漏复用功能\",\"children\":[]}]},{\"level\":2,\"title\":\"LED控制\",\"slug\":\"led控制\",\"link\":\"#led控制\",\"children\":[]},{\"level\":2,\"title\":\"蜂鸣器控制\",\"slug\":\"蜂鸣器控制\",\"link\":\"#蜂鸣器控制\",\"children\":[]},{\"level\":2,\"title\":\"按键输入\",\"slug\":\"按键输入\",\"link\":\"#按键输入\",\"children\":[]}],\"readingTime\":{\"minutes\":2.17,\"words\":650},\"filePathRelative\":\"study/STM32/GPIO/IO口介绍.md\",\"localizedDate\":\"2020年1月1日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
