export const data = JSON.parse("{\"key\":\"v-c2f0397a\",\"path\":\"/study/note/math/%E6%9E%81%E9%99%90.html\",\"title\":\"函数、极限、连续\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"函数、极限、连续\",\"icon\":\"T-Box\",\"order\":1,\"author\":\"张凯博\",\"date\":\"2023-10-01T00:00:00.000Z\",\"footer\":\"函数、极限、连续\",\"copyright\":\"无版权\",\"description\":\"一、函数极限 性质的使用 1. 极限是个常数 2. 局部有界 3. 局部保号 极限存在的判断 左右极限存在且相等 极限值的计算 1. 泰勒公式 $f(x)=f(0)+f'(0)x+\\\\dfrac{1}{2!}f''(0)x^2+\\\\cdots +\\\\dfrac{1}{n!}f^{(n)}(0)x^n$ $e^x=1+x+\\\\frac{1}{2}x^2$ $ln...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/docs/study/note/math/%E6%9E%81%E9%99%90.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"文档管理\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"函数、极限、连续\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"一、函数极限 性质的使用 1. 极限是个常数 2. 局部有界 3. 局部保号 极限存在的判断 左右极限存在且相等 极限值的计算 1. 泰勒公式 $f(x)=f(0)+f'(0)x+\\\\dfrac{1}{2!}f''(0)x^2+\\\\cdots +\\\\dfrac{1}{n!}f^{(n)}(0)x^n$ $e^x=1+x+\\\\frac{1}{2}x^2$ $ln...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"张凯博\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-10-01T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"函数、极限、连续\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-10-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"张凯博\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、函数极限\",\"slug\":\"一、函数极限\",\"link\":\"#一、函数极限\",\"children\":[{\"level\":3,\"title\":\"性质的使用\",\"slug\":\"性质的使用\",\"link\":\"#性质的使用\",\"children\":[]},{\"level\":3,\"title\":\"极限存在的判断\",\"slug\":\"极限存在的判断\",\"link\":\"#极限存在的判断\",\"children\":[]},{\"level\":3,\"title\":\"极限值的计算\",\"slug\":\"极限值的计算\",\"link\":\"#极限值的计算\",\"children\":[]},{\"level\":3,\"title\":\"无穷小\",\"slug\":\"无穷小\",\"link\":\"#无穷小\",\"children\":[]}]},{\"level\":2,\"title\":\"二、数列极限\",\"slug\":\"二、数列极限\",\"link\":\"#二、数列极限\",\"children\":[{\"level\":3,\"title\":\"判断数列收敛性\",\"slug\":\"判断数列收敛性\",\"link\":\"#判断数列收敛性\",\"children\":[]},{\"level\":3,\"title\":\"求数列极限\",\"slug\":\"求数列极限\",\"link\":\"#求数列极限\",\"children\":[]}]},{\"level\":2,\"title\":\"三、极限的应用\",\"slug\":\"三、极限的应用\",\"link\":\"#三、极限的应用\",\"children\":[{\"level\":3,\"title\":\"连续性判断\",\"slug\":\"连续性判断\",\"link\":\"#连续性判断\",\"children\":[]},{\"level\":3,\"title\":\"间断点\",\"slug\":\"间断点\",\"link\":\"#间断点\",\"children\":[]},{\"level\":3,\"title\":\"渐近线\",\"slug\":\"渐近线\",\"link\":\"#渐近线\",\"children\":[]}]}],\"readingTime\":{\"minutes\":2.54,\"words\":761},\"filePathRelative\":\"study/note/math/极限.md\",\"localizedDate\":\"2023年10月1日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
