export const data = JSON.parse("{\"key\":\"v-81cd3fde\",\"path\":\"/study/note/line/%E7%9F%A9%E9%98%B5.html\",\"title\":\"矩阵\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"矩阵\",\"icon\":\"Tennis\",\"order\":2,\"author\":\"张凯博\",\"date\":\"2020-01-01T00:00:00.000Z\",\"footer\":\"矩阵\",\"copyright\":\"无版权\",\"description\":\"一、常用矩阵变换公式 $AA^=A^A=AE$ $(AB)^{-1}=B^{-1}A^{-1}$ $(AB)^T=B^TA^T$ $(AB)^=B^A^*$ 二、矩阵的初等变换 行变换：左乘初等矩阵 列变换：右乘初等矩阵 三、矩阵的n次幂 情况一：$A$为方阵，$r(A)=1$ $A^n=[tr(A)]^{n-1}A$ 情况二：计算$A^2$ 若$A^...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/docs/study/note/line/%E7%9F%A9%E9%98%B5.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"文档管理\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"矩阵\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"一、常用矩阵变换公式 $AA^=A^A=AE$ $(AB)^{-1}=B^{-1}A^{-1}$ $(AB)^T=B^TA^T$ $(AB)^=B^A^*$ 二、矩阵的初等变换 行变换：左乘初等矩阵 列变换：右乘初等矩阵 三、矩阵的n次幂 情况一：$A$为方阵，$r(A)=1$ $A^n=[tr(A)]^{n-1}A$ 情况二：计算$A^2$ 若$A^...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"张凯博\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2020-01-01T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"矩阵\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2020-01-01T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"张凯博\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、常用矩阵变换公式\",\"slug\":\"一、常用矩阵变换公式\",\"link\":\"#一、常用矩阵变换公式\",\"children\":[]},{\"level\":2,\"title\":\"二、矩阵的初等变换\",\"slug\":\"二、矩阵的初等变换\",\"link\":\"#二、矩阵的初等变换\",\"children\":[]},{\"level\":2,\"title\":\"三、矩阵的n次幂\",\"slug\":\"三、矩阵的n次幂\",\"link\":\"#三、矩阵的n次幂\",\"children\":[]},{\"level\":2,\"title\":\"四、矩阵的逆\",\"slug\":\"四、矩阵的逆\",\"link\":\"#四、矩阵的逆\",\"children\":[{\"level\":3,\"title\":\"性质\",\"slug\":\"性质\",\"link\":\"#性质\",\"children\":[]},{\"level\":3,\"title\":\"求矩阵的逆\",\"slug\":\"求矩阵的逆\",\"link\":\"#求矩阵的逆\",\"children\":[]}]},{\"level\":2,\"title\":\"五、矩阵的伴随\",\"slug\":\"五、矩阵的伴随\",\"link\":\"#五、矩阵的伴随\",\"children\":[]},{\"level\":2,\"title\":\"六、矩阵的秩\",\"slug\":\"六、矩阵的秩\",\"link\":\"#六、矩阵的秩\",\"children\":[]},{\"level\":2,\"title\":\"七、分块矩阵\",\"slug\":\"七、分块矩阵\",\"link\":\"#七、分块矩阵\",\"children\":[]}],\"readingTime\":{\"minutes\":2.9,\"words\":870},\"filePathRelative\":\"study/note/line/矩阵.md\",\"localizedDate\":\"2020年1月1日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
