export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"项目主页","i":"home"},["/README.md"]],
  ["v-1473bf53","/demo/",{"y":"a","t":"主要功能与配置演示","i":"laptop-code"},["/demo/README.md"]],
  ["v-4e65ec78","/demo/disable.html",{"y":"a","t":"布局与功能禁用","i":"gears","O":3},[":md"]],
  ["v-c151bf32","/demo/encrypt.html",{"y":"a","t":"密码加密的文章","i":"lock"},[":md"]],
  ["v-438ffe52","/demo/markdown.html",{"y":"a","t":"Markdown 展示","i":"fab fa-markdown","O":2},[":md"]],
  ["v-6e19edb7","/demo/page.html",{"y":"a","t":"页面配置","i":"file","O":1},[":md"]],
  ["v-d7188082","/study/",{"y":"a","t":"学习笔记","i":"laptop-code"},["/study/README.md"]],
  ["v-ca04c7b8","/program/",{"y":"a","t":"项目","i":"laptop-code"},["/program/README.md"]],
  ["v-fffb8e28","/guide/",{"y":"a","t":"指南","i":"lightbulb"},["/guide/README.md"]],
  ["v-e4621184","/study/exams/01.html",{"y":"a","t":"函数","i":"file","O":1},[":md"]],
  ["v-2350eefa","/study/exams/",{"y":"a","t":"复习笔记","i":"laptop-code"},["/study/exams/README.md"]],
  ["v-6997a930","/program/STM32/01.html",{"y":"a","t":"STM32","i":"file","O":1},[":md"]],
  ["v-0fc2ad70","/program/STM32/",{"y":"a","t":"STM32教程","i":"laptop-code"},["/program/STM32/README.md"]],
  ["v-5d5c2d30","/guide/bar/",{"y":"a","t":"Bar 功能","i":"lightbulb"},["/guide/bar/README.md"]],
  ["v-177e1f06","/guide/bar/baz.html",{"y":"a","t":"Baz","i":"circle-info"},[":md"]],
  ["v-5d5821d6","/guide/foo/",{"y":"a","t":"Foo 功能","i":"lightbulb"},["/guide/foo/README.md"]],
  ["v-0b6fc5f8","/guide/foo/ray.html",{"y":"a","t":"Ray","i":"circle-info"},[":md"]],
  ["v-48f243f1","/program/smart_door/01.html",{"y":"a","t":"door1","i":"file","O":2},[":md"]],
  ["v-4aa71c90","/program/smart_door/02.html",{"y":"a","t":"door2","i":"file","O":3},[":md"]],
  ["v-4c5bf52f","/program/smart_door/03.html",{"y":"a","t":"door3","i":"file","O":4},[":md"]],
  ["v-31731a40","/program/STM32/introduce/01.html",{"y":"a","t":"STM32introduce","i":"file","O":1},[":md"]],
  ["v-10294a38","/program/STM32/introduce/",{"y":"a","t":"STM32introduce","i":"laptop-code"},["/program/STM32/introduce/README.md"]],
  ["v-0780107e","/program/smart_door/introduce/01.html",{"y":"a","t":"STM32introduce","i":"file","O":1},[":md"]],
  ["v-00e82bd7","/program/smart_door/introduce/",{"y":"a","t":"墨水屏","i":"laptop-code"},["/program/smart_door/introduce/README.md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-3e0394b2","/program/smart_door/",{"y":"p","t":"Smart Door"},[]],
]
