export const data = JSON.parse("{\"key\":\"v-754f1286\",\"path\":\"/study/note/probability/%E4%B8%80%E7%BB%B4%E9%9A%8F%E6%9C%BA%E5%8F%98%E9%87%8F%E5%8F%8A%E5%85%B6%E5%88%86%E5%B8%83.html\",\"title\":\"一维随机变量\",\"lang\":\"zh-CN\",\"frontmatter\":{\"title\":\"一维随机变量\",\"icon\":\"Boxing\",\"order\":2,\"author\":\"张凯博\",\"date\":\"2023-09-12T00:00:00.000Z\",\"description\":\"一、一维随机变量及其分布 分布函数 $F(x)=P(X \\\\le x)$ 分布函数性质: 1. $\\\\forall x1 < x2,\\\\text{则}F(x1)\\\\le F(x2)$ 2. $0 \\\\le F(x)\\\\le 1$ 3. $\\\\lim{x \\\\to -\\\\infty } F(x)=0;\\\\lim{x \\\\to \\\\infty } F(x)=1$ 4. $\\\\lim...\",\"head\":[[\"meta\",{\"property\":\"og:url\",\"content\":\"https://vuepress-theme-hope-docs-demo.netlify.app/docs/study/note/probability/%E4%B8%80%E7%BB%B4%E9%9A%8F%E6%9C%BA%E5%8F%98%E9%87%8F%E5%8F%8A%E5%85%B6%E5%88%86%E5%B8%83.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"文档管理\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"一维随机变量\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"一、一维随机变量及其分布 分布函数 $F(x)=P(X \\\\le x)$ 分布函数性质: 1. $\\\\forall x1 < x2,\\\\text{则}F(x1)\\\\le F(x2)$ 2. $0 \\\\le F(x)\\\\le 1$ 3. $\\\\lim{x \\\\to -\\\\infty } F(x)=0;\\\\lim{x \\\\to \\\\infty } F(x)=1$ 4. $\\\\lim...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"property\":\"article:author\",\"content\":\"张凯博\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2023-09-12T00:00:00.000Z\"}],[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"一维随机变量\\\",\\\"image\\\":[\\\"\\\"],\\\"datePublished\\\":\\\"2023-09-12T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"张凯博\\\"}]}\"]]},\"headers\":[{\"level\":2,\"title\":\"一、一维随机变量及其分布\",\"slug\":\"一、一维随机变量及其分布\",\"link\":\"#一、一维随机变量及其分布\",\"children\":[{\"level\":3,\"title\":\"分布函数\",\"slug\":\"分布函数\",\"link\":\"#分布函数\",\"children\":[]},{\"level\":3,\"title\":\"分布律\",\"slug\":\"分布律\",\"link\":\"#分布律\",\"children\":[]},{\"level\":3,\"title\":\"概率密度\",\"slug\":\"概率密度\",\"link\":\"#概率密度\",\"children\":[]},{\"level\":3,\"title\":\"常见分布\",\"slug\":\"常见分布\",\"link\":\"#常见分布\",\"children\":[]}]},{\"level\":2,\"title\":\"二、一维随机变量函数的分布\",\"slug\":\"二、一维随机变量函数的分布\",\"link\":\"#二、一维随机变量函数的分布\",\"children\":[]}],\"readingTime\":{\"minutes\":1.5,\"words\":449},\"filePathRelative\":\"study/note/probability/一维随机变量及其分布.md\",\"localizedDate\":\"2023年9月12日\",\"autoDesc\":true}")

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
